runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: www/resilience.html
  upload: www/resilience.html

- url: /(.*)
  static_files: www/\1
  upload: www/(.*)